Start-Process pwsh -ArgumentList '-NoExit', '-Command', 'dotnet watch run --project Playground.Server/Playground.Server.csproj --urls=http://localhost:5018'
Start-Process pwsh -ArgumentList '-NoExit', '-Command', 'dotnet watch run --project Playground.User/Playground.User.csproj --urls=http://localhost:5159'
Start-Process pwsh -ArgumentList '-NoExit', '-Command', 'dotnet watch run --project Playground.Catalog/Playground.Catalog.csproj --urls=http://localhost:5001'
Start-Process pwsh -ArgumentList '-NoExit', '-Command', 'dotnet watch run --project Playground.Cart/Playground.Cart.csproj --urls=http://localhost:5020'
Start-Process pwsh -ArgumentList '-NoExit', '-Command', 'dotnet watch run --project Playground.WishList/Playground.WishList.csproj --urls=http://localhost:5021'
Start-Process pwsh -ArgumentList '-NoExit', '-Command', 'dotnet watch run --project Playground.Gateway/Playground.Gateway.csproj --urls=http://localhost:7000'
Start-Process pwsh -ArgumentList '-NoExit', '-Command', 'cd playground.client; npm install; npm run dev'